name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}
          docker build . -t $DOCKER_REPOSITORY/$DOCKER_USERNAME/tem-docker-public:$TAG
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}

          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REPOSITORY" -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_REPOSITORY/$DOCKER_USERNAME/tem-docker-public:$TAG
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Testando Images
        run: echo "Entrei na feira da fruta"

      - name: Update deployment config 
        run: sed -i s/:latest/:${GITHUB_SHA:0:8}/ k8s/deployment.yaml
        if: github.ref == 'refs/heads/master'

      - name: Deploy
        uses: danielr1996/kubectl-action@1.0.0
        if: github.ref == 'refs/heads/master'
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f k8s