name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}
          docker build . -t $DOCKER_REPOSITORY/$DOCKER_USERNAME/tem-docker-public:$TAG
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Push Docker image
        run: |
          export TAG=${GITHUB_SHA:0:8}

          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REPOSITORY" -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_REPOSITORY/$DOCKER_USERNAME/tem-docker-public:$TAG
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Testando Images
        run: echo "Entrei na feira da fruta"

      - name: Update deployment config 
        run: sed -i s/:latest/:${GITHUB_SHA:0:8}/ k8s/deployment.yml
        if: github.ref == 'refs/heads/master'

      - name: Deploy
        run: |
          curl --silent https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl --output /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl
          curl --silent https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator --output /usr/local/bin/aws-iam-authenticator
          chmod +x /usr/local/bin/aws-iam-authenticator
          mkdir -p ~/.kube
          echo $KUBECONFIG | base64 -d > ~/.kube/config
          kubectl apply -f k8s
        if: github.ref == 'refs/heads/master'
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        